name: Build and Publish to PyPI

on:
  push:
    branches:
      - main  
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Build wheel
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
